# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["current"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: merca/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: merca
          template: classicblank
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Oslo
          plugin_introduction: yes

          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent

          plugin_code: yes
          plugin_code_languages: pyhton, csharp
          plugin_code_load: 400

          plugin_traffic: yes

          plugin_repositories: yes
          plugin_repositories_featured: merca/pyaduro

          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1

          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
